create:
#	protoc --proto_path=proto proto/*.proto --go_out=gen/
#	protoc --proto_path=proto proto/*.proto --go-grpc_out=gen/

	protoc --go_out=. --go_opt=paths=source_relative \
        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
        proto/inmemoryservice.proto

clean:
	rm gen/proto/*.go