// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/danieloluwadare/tyk-cocnurrent-parser-service/gen/proto"
)

// InMemoryServiceClient is an autogenerated mock type for the InMemoryServiceClient type
type InMemoryServiceClient struct {
	mock.Mock
}

// SaveRequest provides a mock function with given fields: ctx, in, opts
func (_m *InMemoryServiceClient) SaveRequest(ctx context.Context, in *proto.TykServerRequest, opts ...grpc.CallOption) (*proto.TykServerResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.TykServerResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.TykServerRequest, ...grpc.CallOption) *proto.TykServerResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TykServerResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.TykServerRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewInMemoryServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewInMemoryServiceClient creates a new instance of InMemoryServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInMemoryServiceClient(t mockConstructorTestingTNewInMemoryServiceClient) *InMemoryServiceClient {
	mock := &InMemoryServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
