// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeInMemoryServiceServer is an autogenerated mock type for the UnsafeInMemoryServiceServer type
type UnsafeInMemoryServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedInMemoryServiceServer provides a mock function with given fields:
func (_m *UnsafeInMemoryServiceServer) mustEmbedUnimplementedInMemoryServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeInMemoryServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeInMemoryServiceServer creates a new instance of UnsafeInMemoryServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeInMemoryServiceServer(t mockConstructorTestingTNewUnsafeInMemoryServiceServer) *UnsafeInMemoryServiceServer {
	mock := &UnsafeInMemoryServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
