// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: proto/inmemoryservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the task's name and description
type TykServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *TykServerRequest) Reset() {
	*x = TykServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inmemoryservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TykServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TykServerRequest) ProtoMessage() {}

func (x *TykServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inmemoryservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TykServerRequest.ProtoReflect.Descriptor instead.
func (*TykServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_inmemoryservice_proto_rawDescGZIP(), []int{0}
}

func (x *TykServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TykServerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// The response message from the server
type TykServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TykServerResponse) Reset() {
	*x = TykServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inmemoryservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TykServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TykServerResponse) ProtoMessage() {}

func (x *TykServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inmemoryservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TykServerResponse.ProtoReflect.Descriptor instead.
func (*TykServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_inmemoryservice_proto_rawDescGZIP(), []int{1}
}

func (x *TykServerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_inmemoryservice_proto protoreflect.FileDescriptor

var file_proto_inmemoryservice_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d,
	0x61, 0x69, 0x6e, 0x22, 0x48, 0x0a, 0x10, 0x54, 0x79, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x27, 0x0a,
	0x11, 0x54, 0x79, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x53, 0x0a, 0x0f, 0x49, 0x6e, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x53, 0x61, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x54, 0x79, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x79, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_inmemoryservice_proto_rawDescOnce sync.Once
	file_proto_inmemoryservice_proto_rawDescData = file_proto_inmemoryservice_proto_rawDesc
)

func file_proto_inmemoryservice_proto_rawDescGZIP() []byte {
	file_proto_inmemoryservice_proto_rawDescOnce.Do(func() {
		file_proto_inmemoryservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_inmemoryservice_proto_rawDescData)
	})
	return file_proto_inmemoryservice_proto_rawDescData
}

var file_proto_inmemoryservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_inmemoryservice_proto_goTypes = []interface{}{
	(*TykServerRequest)(nil),  // 0: main.TykServerRequest
	(*TykServerResponse)(nil), // 1: main.TykServerResponse
}
var file_proto_inmemoryservice_proto_depIdxs = []int32{
	0, // 0: main.InmemoryService.SaveRequest:input_type -> main.TykServerRequest
	1, // 1: main.InmemoryService.SaveRequest:output_type -> main.TykServerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inmemoryservice_proto_init() }
func file_proto_inmemoryservice_proto_init() {
	if File_proto_inmemoryservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_inmemoryservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TykServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inmemoryservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TykServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_inmemoryservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inmemoryservice_proto_goTypes,
		DependencyIndexes: file_proto_inmemoryservice_proto_depIdxs,
		MessageInfos:      file_proto_inmemoryservice_proto_msgTypes,
	}.Build()
	File_proto_inmemoryservice_proto = out.File
	file_proto_inmemoryservice_proto_rawDesc = nil
	file_proto_inmemoryservice_proto_goTypes = nil
	file_proto_inmemoryservice_proto_depIdxs = nil
}
